[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Andrey Tarasov <andrey13.tarasov@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.9.1"
